<<<<<<< HEAD
dump_dir: /fsx-scaling/sanaelotfi/weight_shared_llms/checkpoints/final_runs/attn_sharing/1b_exps/Baseline_1b_new
name: Baseline_1b
steps: 84000
probe_freq: null
=======
dump_dir: /home/jovyan/workspace/efficient_llms_dumps/1b_exps/baseline
name: Baseline_1B
steps: 42000
probe_freq: 5000
>>>>>>> e131eb0620498b5a088e1e4f6a9b80006ee64eff
seed: 777
optim:
    lr: 3e-4
    warmup: 2000
    lr_min_ratio: 1.0
    clip: 10.0
distributed:
    fsdp_type: no_shard
    dp_shard: 1
    dp_replicate: 8
    compile: true
    model_dtype: bf16
    matmul_allow_tf32: false
    selective_activation_checkpointing: false
    tp_size: 1
model:
    dim: 1536
    ffn_dim_multiplier: 1.125
    n_layers: 36
    n_heads: 16
    n_kv_heads: 8
    attn_sharing: false
    head_sharing: false
data:
    root_dir: /fsx-checkpoints/sanaelotfi/data
    sources:
        fineweb_edu_10bt_shuffled: 1.0
    batch_size: 8
    prefetch_size: 32
    seq_len: 2048
    n_views: 2
    load_async: true
    tokenizer:
        name: sp
        path: /fsx-checkpoints/sanaelotfi/tokenizers/llama2_tokenizer/tokenizer.model
profiling:
    run: true
checkpoint:
    dump:
        every: 8400
        keep: 1
    eval:
        every: 1680
        keep: 1
logging:
    freq: 1000
    wandb:
        project: attn_sharing
        entity: sanaelotfi
        name: Baseline_1b
eval:
    validation:
        max_steps: 1000
