[project]
name = "lingua"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datatrove>=0.5.0",
    "huggingface-hub>=0.32.4",
    "orjson>=3.10.18",
    "pyarrow>=20.0.0",
]
