dump_dir: /home/jovyan/workspace/efficient_llms_dumps/distill_exps/debug_0
name: Baseline
steps: 10500
probe_freq: 5000
seed: 777
optim:
    lr: 3e-4
    warmup: 2000
    lr_min_ratio: 1.0
    clip: 10.0
distributed:
    fsdp_type: no_shard
    dp_shard: 1
    dp_replicate: 7
    compile: true
    model_dtype: bf16
    matmul_allow_tf32: false
    selective_activation_checkpointing: false
    tp_size: 1
model:
    dim: 512
    ffn_dim_multiplier: 1.125
    n_layers: 12
    n_heads: 16
    n_kv_heads: 8
    attn_sharing: true
    head_sharing: true
    qkv_sharing: null
    grouping: 1
    rank: 8
    two_step: false
data:
    root_dir: /home/jovyan/shared/muchane/fineweb-lingua
    sources:
        fineweb_edu_shuffled: 1.0
    batch_size: 16
    prefetch_size: 32
    seq_len: 2048
    n_views: 2
    load_async: true
    tokenizer:
        name: hf
        path: Qwen/Qwen3-0.6B-Base
    #    name: tiktoken
    #    path: /home/jovyan/shared/muchane/lingua-repo/old/llama3-tokenizer/original/tokenizer.model
profiling:
    run: true
checkpoint:
    dump:
        every: 5000
        keep: 1
    eval:
        every: 5000
        keep: 1
eval: null
