dump_dir: /rds/general/user/gts124/home/Efficient-LLMs/checkpoints/projections/projection_baseline_MARK
name: projection_baseline_MARK
steps: 10500
probe_freq: null
seed: 777
optim:
    lr: 3e-4
    warmup: 2000
    lr_min_ratio: 1.0
    clip: 10.0
distributed:
    fsdp_type: no_shard
    dp_shard: 1
    dp_replicate: 8
    compile: true
    model_dtype: bf16
    matmul_allow_tf32: false
    selective_activation_checkpointing: false
    tp_size: 1
model:
    dim: 512 
    ffn_dim_multiplier: 1.0
    n_layers: 8
    n_heads: 16
    n_kv_heads: 8
    weight_tying: True  
    factorised_vocab:
        d_emb: 16 # Dim of vocab matrix
        factorise: True #
        d_factorised: 32  # Output of factorised up-projection
        proj_out: True  # Whether to use down-projection before we reach unembeddings
    project_up_layers:  # 
        - d_attn_kq: 4  
          d_attn_val: 8
          d_attn_out: 256
          d_ffn: 512
data:
    root_dir: /rds/general/user/gts124/ephemeral/redownload_fwedu_10b_data
    sources:
        fineweb_edu_10bt_shuffled: 1.0
    batch_size: 32
    prefetch_size: 32
    seq_len: 2048
    n_views: 2
    load_async: true
    tokenizer:
        name: tiktoken
        # path: /home/jovyan/shared/muchane/lingua-repo/old/llama3-tokenizer/original/tokenizer.model
        path: /rds/general/user/gts124/home/Efficient-LLMs/llama3_tokenizer/original/tokenizer.model

profiling:
    run: true
checkpoint:
    dump:
        every: 10500
        keep: 1
    eval:
        every: 15000
        keep: 1
logging:
    freq: 500
    wandb:
        project: ffn_output_tests
        entity: gts124-imperial-college-london
        name: projection_baseline_MARK
eval: null

# ------------------------------------------------------------------------------------------------------------------------------------------------


# dump_dir: /rds/general/user/gts124/home/Efficient-LLMs/checkpoints/rrt_debugging/hierarchical_FORWARDPASS
# name: "hierarchical_FORWARDPASS"
# steps: 10000
# probe_freq: 2000
# seed: 777
# optim:
#     lr: 3e-4
#     warmup: 2000
#     lr_min_ratio: 0.000001
#     clip: 10.0

# distributed:
#     fsdp_type: full_shard
#     compile: true
#     model_dtype: bf16
#     matmul_allow_tf32: false
#     selective_activation_checkpointing: false
#     tp_size: 1

# model:
#     dim: 768
#     n_layers: 12
#     n_heads: 8
#     rank: 25
#     layer_groups: [[0], [1, 2], [3, 4, 5], [6, 7, 8, 9, 10, 11]]
#     lora_rank: 0

# data:
#     root_dir: /rds/general/user/gts124/ephemeral/redownload_fwedu_10b_data
#     sources:
#         # fineweb_edu_10bt: 1.0
#         fineweb_edu_10bt_shuffled: 1.0
#     batch_size: 16
#     prefetch_size: 64
#     seq_len: 2048
#     n_views: 2
#     load_async: true
#     tokenizer: 
#         path: /rds/general/user/gts124/home/Efficient-LLMs/llama3_tokenizer 
#         # path: /home/jovyan/shared/muchane/lingua-repo/old/llama3-tokenizer/original/tokenizer.model
#         name: bytes

# profiling:
#     run: true

# checkpoint:
#     dump:
#         every: 2000
#         keep: 1
#     eval:
#         every: 10000
#         keep: 10

# logging:
#     freq: 100
#     wandb:
#         project: rrt_debugging
#         entity: gts124-imperial-college-london
#         name: hierarchical_FORWARDPASS

# eval:
#     generator:
#         max_tokens: 8192
#         dtype: bf16
#         temperature: 1.0
#         top_p: 0.95
#     harness:
#         tasks:
#             - hellaswag
#             - piqa
#             - task: nq_open
#               num_fewshot: 5
#     validation:
#         max_steps: 1000
