dump_dir: /home/jovyan/shared/muchane/lingua-repo/dumps/lr_vocab/proj_exps/just_v_0
name: Just_V
steps: 10500
probe_freq: null
seed: 777
optim:
    lr: 3e-4
    warmup: 2000
    lr_min_ratio: 1.0
    clip: 10.0
distributed:
    fsdp_type: no_shard
    dp_shard: 1
    dp_replicate: 8
    compile: true
    model_dtype: bf16
    matmul_allow_tf32: false
    selective_activation_checkpointing: false
    tp_size: 1
model:
    dim: 384
    ffn_dim_multiplier: 0.75
    n_layers: 20
    n_heads: 16
    n_kv_heads: 8
    weight_tying: True
    factorised_vocab:
        d_emb: 16
        factorise: False
        d_factorised: 384
        proj_out: True
    project_up_layers:
        - d_attn_kq: null
          d_attn_val: 24
          d_attn_out: null
          d_ffn: null
data:
    root_dir: /home/jovyan/shared/muchane/fineweb-lingua
    sources:
        fineweb_edu_shuffled: 1.0
    batch_size: 32
    prefetch_size: 32
    seq_len: 2048
    n_views: 2
    load_async: true
    tokenizer:
        name: tiktoken
        path: /home/jovyan/shared/muchane/lingua-repo/old/llama3-tokenizer/original/tokenizer.model

profiling:
    run: true
checkpoint:
    dump:
        every: 10500
        keep: 1
    eval:
        every: 15000
        keep: 1
logging:
    freq: 500
    wandb:
        project: 40m_baseline
        entity: muchanem
        name: 40M_DDP_run_0
eval: null
