name: debug
steps: 60000
probe_freq: null
seed: 777
optim:
  lr: 0.003
  weight_decay: 0.033
  warmup: 5000
  lr_min_ratio: 1.0e-06
  clip: 1.0
distributed:
  fsdp_type: full_shard
  compile: true
  model_dtype: bf16
  matmul_allow_tf32: false
  selective_activation_checkpointing: true
  tp_size: 1
model:
  dim: 2048
  n_heads: 32
  n_groups: 1
  state_dim: 128
  conv_size: 4
  n_layers: 50
  dt_bias: false
  D_has_head_dim: false
  init_args:
    A_init_min: 0.01
    A_init_max: 2
data:
  root_dir: data/shuffled
  sources:
    dclm_baseline_1.0: 100.0
  batch_size: 4
  prefetch_size: 1024
  seq_len: 4096
  n_views: 2
  load_async: true
  add_bos: true
  add_eos: true
  tokenizer:
    name: tiktoken
    path: tokenizers/cl_toplang_128k.tiktoken
profiling:
  run: true
checkpoint:
  dump:
    every: 2500
    keep: 3
  eval:
    every: 5000
    keep: 2
logging:
  freq: 1
async_eval_gpus: 8
eval:
  harness:
    tasks:
    - hellaswag
    - task: boolq
      dataset_kwargs:
        trust_remote_code: true
    - piqa
    - task: social_iqa
      dataset_kwargs:
        trust_remote_code: true
    - winogrande
    - openbookqa
    - arc_easy
    - arc_challenge
    - race
    - commonsense_qa
    - copa
  validation:
    max_steps: 1000
  generator:
    compile_prefilling: false
    reduce_generation_overhead: true
    max_tokens: 16384
    dtype: bf16
