# Template config, need to change dump_dir, data.root_dir and data.tokenizer.path

dump_dir: /net/projects2/interp/efficient_llms_dumps/125m_runs/6-17_1
name: "125M_Baseline_tied"
steps: 763000
probe_freq: 5000
seed: 777
optim:
    lr: 3e-4
    warmup: 2000
    lr_min_ratio: 0.000001
    clip: 10.0

distributed:
    #fsdp_type: full_shard
    # Change fsdp_type to no_shard to mimic DDP behavior
    fsdp_type: no_shard

    # When using no_shard, dp_shard must be 1
    dp_shard: 1

    # dp_replicate should be your total number of GPUs
    dp_replicate: 1
    compile: true
    model_dtype: bf16
    matmul_allow_tf32: false
    selective_activation_checkpointing: false
    tp_size: 1

model:
    dim: 768
    ffn_dim_multiplier: 1.25
    n_layers: 12
    n_heads: 16
    n_kv_heads: 8
    weight_tying: true

data:
    root_dir: /net/projects2/interp/Efficient-LLMs/data
    sources:
        fineweb_edu_10bt_shuffled: 1.0
    batch_size: 48
    prefetch_size: 16
    seq_len: 2048
    n_views: 2
    load_async: true
    tokenizer:
        name: sp
        path: /net/projects2/interp/Efficient-LLMs/tokenizer/llama2/tokenizer.model

profiling:
    run: true

checkpoint:
    dump:
        every: 5000
        keep: 1
    eval:
        every: 5000
        keep: 1

logging:
    freq: 500
    wandb:
        project: "40m_baseline"
        entity: "muchanem" # e.g., 'jovyan'
        name: "40M_DDP_run_0"

eval:
    generator:
        max_tokens: 8192
        dtype: bf16
        temperature: 1.0
        top_p: 0.95
    harness:
        tasks:
            - hellaswag
            - piqa
            - task: nq_open
              num_fewshot: 5
    validation: null
#        max_steps: 100
