dump_dir: /home/jovyan/workspace/efficient_llms_dumps/40m_runs/6-17_0
name: 40M_Baseline_tied
steps: 763000
probe_freq: 5000
seed: 777
optim:
  lr: 3e-4
  warmup: 2000
  lr_min_ratio: 1.0e-06
  clip: 10.0
distributed:
  fsdp_type: no_shard
  dp_shard: 1
  dp_replicate: 4
  compile: true
  model_dtype: bf16
  matmul_allow_tf32: false
  selective_activation_checkpointing: false
  tp_size: 1
model:
  dim: 512
  ffn_dim_multiplier: 1.125
  n_layers: 12
  n_heads: 16
  n_kv_heads: 8
  weight_tying: true
data:
  root_dir: /home/jovyan/workspace/Efficient-LLMs/data
  sources:
    fineweb_edu_10bt_shuffled: 1.0
  batch_size: 64
  prefetch_size: 32
  seq_len: 2048
  n_views: 2
  load_async: true
  tokenizer:
    name: sp
    path: /home/jovyan/workspace/Efficient-LLMs/tokenizer/llama2/tokenizer.model
profiling:
  run: true
checkpoint:
  dump:
    every: 5000
    keep: 1
  eval:
    every: 5000
    keep: 1
logging:
  freq: 500
  wandb:
    project: 40m_baseline
    entity: muchanem
    name: 40M_DDP_run_0
eval:
  generator:
    max_tokens: 8192
    dtype: bf16
    temperature: 1.0
    top_p: 0.95
  harness:
    tasks:
    - hellaswag
    - piqa
    - task: nq_open
      num_fewshot: 5
  validation: null
