dump_dir: /checkpoint/optim/sanaelotfi/weight_shared_llms/checkpoints/colm_runs/LAYERWISE_v3/500M/156M_small
name: 156M_small
steps: 76300
probe_freq: null
seed: 777
optim:
  lr: 3e-4
  warmup: 2000
  lr_min_ratio: 1.0e-06
  clip: 10.0
distributed:
  fsdp_type: no_shard
  compile: true
  model_dtype: bf16
  matmul_allow_tf32: false
  selective_activation_checkpointing: false
  tp_size: 1
  dp_replicate: 8
  dp_shard: 1
model:
  dim: 992
  ffn_dim_multiplier: 1.125
  n_layers: 16
  n_heads: 12
  rank: 0
  weight_tying: false
  layer_groups:
  - - 0
  - - 1
  - - 2
  - - 3
  - - 4
  - - 5
  - - 6
  - - 7
  - - 8
  - - 9
  - - 10
  - - 11
  - - 12
  - - 13
  - - 14
  - - 15
  lora_rank: 0
data:
  root_dir: /checkpoint/optim/sanaelotfi/data
  sources:
    hq_data_20bt: 1.0
  batch_size: 16
  prefetch_size: 32
  seq_len: 2048
  n_views: 2
  load_async: true
  tokenizer:
    path: /checkpoint/optim/sanaelotfi/tokenizers/llama3_tokenizer/original/tokenizer.model
    name: tiktoken
profiling:
  run: true
checkpoint:
  dump:
    every: 15260
    keep: 1
  eval:
    every: 1536
    keep: 1
logging:
  freq: 100
  wandb:
    project: colm-experiments
    entity: weight-sharing
    name: 156M_small
eval:
  validation:
    max_steps: null
