
dump_dir: /rds/general/user/gts124/home/Efficient-LLMs/checkpoints/lora_rank/rank_40
name: "rank_40"
steps: 10000
probe_freq: 2000
seed: 777
optim:
    lr: 3e-4
    warmup: 2000
    lr_min_ratio: 0.000001
    clip: 10.0

distributed:
    fsdp_type: full_shard
    compile: true
    model_dtype: bf16
    matmul_allow_tf32: false
    selective_activation_checkpointing: false
    tp_size: 1

model:
    dim: 576
    n_layers: 12
    n_heads: 8
    rank: 25
    layer_groups: [[0, 1], [2, 3], [4, 5], [6, 7], [8, 9], [10, 11]]
    lora_rank: 40

data:
    root_dir: /rds/general/user/gts124/ephemeral/redownload_fwedu_10b_data
    sources:
        fineweb_edu_10bt_shuffled: 1.0
    batch_size: 16
    prefetch_size: 64
    seq_len: 2048
    n_views: 2
    load_async: true
    tokenizer: 
        path: /rds/general/user/gts124/home/Efficient-LLMs/llama3_tokenizer 
        name: bytes

profiling:
    run: true

checkpoint:
    dump:
        every: 2000
        keep: 1
    eval:
        every: 10000
        keep: 10

logging:
    freq: 100
    wandb:
        project: rrt_lora_rank
        entity: gts124-imperial-college-london
        name: rank_40

eval:
    generator:
        max_tokens: 8192
        dtype: bf16
        temperature: 1.0
        top_p: 0.95
    harness:
        tasks:
            - hellaswag
            - piqa
            - task: nq_open
              num_fewshot: 5
    validation:
        max_steps: 1000
